---
# moved the following to the freckelize commandline app
# - name: "[check confirmation]"
#   fail: msg="As the ansible-tasks adapter can execute arbitrary code, user confirmation is necessary to  use this adatper. Consult the output of 'freckelize ansible-tasks --help' or XXX for more information."
#   when: ansible_tasks_user_confirmation is not defined or not ansible_tasks_user_confirmation

- name: "[check whether .tasks.freckle file exists]"
  stat:
    path: "{{ freckle_path }}/.tasks.freckle"
  register: default_tasks_file

- name: "[set default task list]"
  set_fact:
     default_task_lists:
         - '.tasks.freckle'
  when: default_tasks_file.stat.exists

- name: "[set default task list]"
  set_fact:
     default_task_lists: []
  when: not default_tasks_file.stat.exists

- name: "[user default task lists]"
  set_fact:
    task_lists: "{{ default_task_lists }}"
  when: not ansible_task_lists

- name: "[use user provided task lists]"
  set_fact:
    task_lists: "{{ ansible_task_lists }}"
  when: ansible_task_lists

- name: "[including tasks]"
  include_tasks: "{{ freckle_path }}/{{ task_file }}"
  with_items:
    - "{{ task_lists }}"
  loop_control:
    loop_var: task_file
